---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# arthistory

<!-- badges: start -->
<!-- badges: end -->

The goal of arthistory is to [fill this in...]

## Installation

You can install the development version of arthistory from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("saralemus7/arthistory")
```

## Datasets

This package contains three datasets:

-   `worksjanson`: Contains individual work-level data by edition of Gardner's art history textbook from 1963 until 2011. For each work, there is information about the size of the work and text as displayed in the textbook as well as details about the work's medium and year created. Demographic data about the artist is also included.

-   `worksgardner`: Contains individual work-level data by edition of Gardner's art history textbook from 1926 until 2020. For each work, there is information about the size of the work as displayed in the textbook as well as the size of the accompanying descriptive text. Demographic data about the artist is also included.

-   `artists`: Contains various information about artists by edition of Gardner or Janson's art history textbook from 1926 until 2020. Data includes demographic information, space occupied in the textbook, as well as presence in the [MoMA](https://www.moma.org/) and [Whitney](https://whitney.org/) museums.
